apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: blog-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80