name: Build and Test
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  checks: write
  issues: read
  pull-requests: write
  actions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for gitversion
          

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/228913880487/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-service@scott-number-6-project.iam.gserviceaccount.com'
          create_credentials_file: true
          token_format: access_token
          
#      - name: configure docker
#        run: gcloud auth configure-docker us-central1-docker.pkg.dev
        
      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-west4-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: europe-west4-docker.pkg.dev/scott-number-6-project/blog/first-blog
          tags: |
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
            
      - name: Test container
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
