name: Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  checks: write
  issues: read
  pull-requests: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: FreeFoxSoftware/actions/initialise@main
      - uses: FreeFoxSoftware/actions/google-login@main
        with:
          federated-identity-project-number: ${{ secrets.FEDERATED_IDENTITY_PROJECT_NUMBER }}

      - uses: FreeFoxSoftware/actions/build-push-tag@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: blog